<template>
    <div class="main">
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
        switch
    </div>
</template>

<style lang="scss">
    .main{
        padding-left: 8px;
    }
</style>